workflows:
  ios-build:
    name: iOS Debug Build
    max_build_duration: 30
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.example.SoccerCoachApp
      vars:
        XCODE_WORKSPACE: SoccerCoachApp.xcodeproj
        XCODE_SCHEME: SoccerCoachApp
    scripts:
      - name: Set up keychain
        script: |
          security create-keychain -p "password" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "password" build.keychain
          security set-keychain-settings
      - name: Build the app
        script: |
          xcodebuild build \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/Debug-iphoneos/*.app
      - build/Debug-iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
