workflows:
  ios-build:
    name: iOS Unsigned Debug Build
    max_build_duration: 30
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: SoccerCoachApp.xcodeproj
        XCODE_SCHEME: SoccerCoachApp
    scripts:
      - name: Build the app without signing
        script: |
          xcodebuild clean build \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE_SPECIFIER=""
    artifacts:
      - build/Debug-iphoneos/*.app
      - build/Debug-iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
