workflows:
  ios-build:
    name: My Soccer Coach iOS App
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_PROJECT: "MySoccerCoachApp.xcodeproj"
        XCODE_SCHEME: "MySoccerCoachApp"
        BUNDLE_ID: "com.example.SoccerCoachApp"
      xcode: 15.0
    scripts:
      - name: Build the app (unsigned)
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -derivedDataPath build \
            clean build
    artifacts:
      - build/Build/Products/Release-iphoneos/*.app
      - build/Build/**/*.dSYM
